#pragma once
#include <map>

#include "Draw.h"
#include "xorstr.hpp"

namespace Hotkey
{
	static std::map<int, std::string> virtualKeyToString = {
		{0x00, xorstr_("Undefined")},
		{0x01, xorstr_("Left Mouse Button")},
		{0x02, xorstr_("Right Mouse Button")},
		{0x03, xorstr_("Control-Break")},
		{0x04, xorstr_("Middle Mouse Button")},
		{0x05, xorstr_("X1 Mouse Button")},
		{0x06, xorstr_("X2 Mouse Button")},
		{0x08, xorstr_("Backspace")},
		{0x09, xorstr_("Tab")},
		{0x0C, xorstr_("Clear")},
		{0x0D, xorstr_("Enter")},
		{0x10, xorstr_("Shift")},
		{0x11, xorstr_("Control")},
		{0x12, xorstr_("Alt")},
		{0x13, xorstr_("Pause")},
		{0x14, xorstr_("Caps Lock")},
		{0x1B, xorstr_("Escape")},
		{0x20, xorstr_("Space")},
		{0x21, xorstr_("Page Up")},
		{0x22, xorstr_("Page Down")},
		{0x23, xorstr_("End")},
		{0x24, xorstr_("Home")},
		{0x25, xorstr_("Left Arrow")},
		{0x26, xorstr_("Up Arrow")},
		{0x27, xorstr_("Right Arrow")},
		{0x28, xorstr_("Down Arrow")},
		{0x29, xorstr_("Select")},
		{0x2A, xorstr_("Print")},
		{0x2B, xorstr_("Execute")},
		{0x2C, xorstr_("Print Screen")},
		{0x2D, xorstr_("Insert")},
		{0x2E, xorstr_("Delete")},
		{0x30, xorstr_("0")},
		{0x31, xorstr_("1")},
		{0x32, xorstr_("2")},
		{0x33, xorstr_("3")},
		{0x34, xorstr_("4")},
		{0x35, xorstr_("5")},
		{0x36, xorstr_("6")},
		{0x37, xorstr_("7")},
		{0x38, xorstr_("8")},
		{0x39, xorstr_("9")},
		{0x41, xorstr_("A")},
		{0x42, xorstr_("B")},
		{0x43, xorstr_("C")},
		{0x44, xorstr_("D")},
		{0x45, xorstr_("E")},
		{0x46, xorstr_("F")},
		{0x47, xorstr_("G")},
		{0x48, xorstr_("H")},
		{0x49, xorstr_("I")},
		{0x4A, xorstr_("J")},
		{0x4B, xorstr_("K")},
		{0x4C, xorstr_("L")},
		{0x4D, xorstr_("M")},
		{0x4E, xorstr_("N")},
		{0x4F, xorstr_("O")},
		{0x50, xorstr_("P")},
		{0x51, xorstr_("Q")},
		{0x52, xorstr_("R")},
		{0x53, xorstr_("S")},
		{0x54, xorstr_("T")},
		{0x55, xorstr_("U")},
		{0x56, xorstr_("V")},
		{0x57, xorstr_("W")},
		{0x58, xorstr_("X")},
		{0x59, xorstr_("Y")},
		{0x5A, xorstr_("Z")},
		{0x5B, xorstr_("Left Windows")},
		{0x5C, xorstr_("Right Windows")},
		{0x5D, xorstr_("Applications")},
		{0x5F, xorstr_("Sleep")},
		{0x60, xorstr_("Numpad 0")},
		{0x61, xorstr_("Numpad 1")},
		{0x62, xorstr_("Numpad 2")},
		{0x63, xorstr_("Numpad 3")},
		{0x64, xorstr_("Numpad 4")},
		{0x65, xorstr_("Numpad 5")},
		{0x66, xorstr_("Numpad 6")},
		{0x67, xorstr_("Numpad 7")},
		{0x68, xorstr_("Numpad 8")},
		{0x69, xorstr_("Numpad 9")},
		{0x6A, xorstr_("Multiply")},
		{0x6B, xorstr_("Add")},
		{0x6C, xorstr_("Separator")},
		{0x6D, xorstr_("Subtract")},
		{0x6E, xorstr_("Decimal")},
		{0x6F, xorstr_("Divide")},
		{0x70, xorstr_("F1")},
		{0x71, xorstr_("F2")},
		{0x72, xorstr_("F3")},
		{0x73, xorstr_("F4")},
		{0x74, xorstr_("F5")},
		{0x75, xorstr_("F6")},
		{0x76, xorstr_("F7")},
		{0x77, xorstr_("F8")},
		{0x78, xorstr_("F9")},
		{0x79, xorstr_("F10")},
		{0x7A, xorstr_("F11")},
		{0x7B, xorstr_("F12")},
		{0x7C, xorstr_("F13")},
		{0x7D, xorstr_("F14")},
		{0x7E, xorstr_("F15")},
		{0x7F, xorstr_("F16")},
		{0x80, xorstr_("F17")},
		{0x81, xorstr_("F18")},
		{0x82, xorstr_("F19")},
		{0x83, xorstr_("F20")},
		{0x84, xorstr_("F21")},
		{0x85, xorstr_("F22")},
		{0x86, xorstr_("F23")},
		{0x87, xorstr_("F24")},
		{0x90, xorstr_("Num Lock")},
		{0x91, xorstr_("Scroll Lock")},
		{0xA0, xorstr_("Left Shift")},
		{0xA1, xorstr_("Right Shift")},
		{0xA2, xorstr_("Left Control")},
		{0xA3, xorstr_("Right Control")},
		{0xA4, xorstr_("Left Menu")},
		{0xA5, xorstr_("Right Menu")},
		{0xA6, xorstr_("Browser Back")},
		{0xA7, xorstr_("Browser Forward")},
		{0xA8, xorstr_("Browser Refresh")},
		{0xA9, xorstr_("Browser Stop")},
		{0xAA, xorstr_("Browser Search")},
		{0xAB, xorstr_("Browser Favorites")},
		{0xAC, xorstr_("Browser Home")},
		{0xAD, xorstr_("Volume Mute")},
		{0xAE, xorstr_("Volume Down")},
		{0xAF, xorstr_("Volume Up")},
		{0xB0, xorstr_("Next Track")},
		{0xB1, xorstr_("Previous Track")},
		{0xB2, xorstr_("Stop Media")},
		{0xB3, xorstr_("Play/Pause Media")},
		{0xB4, xorstr_("Start Mail")},
		{0xB5, xorstr_("Select Media")},
		{0xB6, xorstr_("Start Application 1")},
		{0xB7, xorstr_("Start Application 2")},
		{0xBA, xorstr_(";:")},
		{0xBB, xorstr_("+=")},
		{0xBC, xorstr_(",<")},
		{0xBD, xorstr_("-_")},
		{0xBE, xorstr_(".>")},
		{0xBF, xorstr_("/?")},
		{0xC0, xorstr_("`~")},
		{0xDB, xorstr_("[{")},
		{0xDC, xorstr_("\\|")},
		{0xDD, xorstr_("]}")},
		{0xDE, xorstr_("'\"")},
		{0xDF, xorstr_("Reserved")},
		{0xE5, xorstr_("IME Process")},
		{0xF6, xorstr_("Attn")},
		{0xF7, xorstr_("CrSel")},
		{0xF8, xorstr_("ExSel")},
		{0xF9, xorstr_("Erase EOF")},
		{0xFA, xorstr_("Play")},
		{0xFB, xorstr_("Zoom")},
		{0xFE, xorstr_("Reserved")},
		{0xFF, xorstr_("PA1")},
	};

	enum class KeyState
	{
		None = 1,
		Down,
		Up,
		Pressed
	};

	extern int lastPressedKey;
	extern bool IsDown(int vKey);
	extern bool IsPressed(int vKey);

	extern bool keyboardEvent(UINT uMsg, WPARAM wParam, LPARAM lParam);
}
